[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"

# Deploy previews for all branches
[context.deploy-preview]
  command = "npm run build"

# Production deployment
[context.production]
  command = "npm run build"
